# Generated by Django 5.1.4 on 2024-12-23 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoes',
            old_name='product_video',
            new_name='video',
        ),
    ]
